### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by steveklebanoff** [AugurProject/marketeer#7]
Can't seem to run this.  Using node 8:

```
const marketeer = require('marketeer');

var config = {
  http: "https://mainnet.infura.io/myInfuraUrl",          //specify at least 1 of http, ws, or ipc
  db: "./path_to_db",              //will be created automatically if doesn't exist already
  limit: null,                     //How many markets to fetch (null for all)
  filtering: true,                 //Listen for new markets, price changes, etc? (only used with watch)
  scan: true,                      //Scan blockchain for markets on startup?
}

marketeer.scan(config, function (err, numUpdates) {
  if (err) throw err;
  console.log("Oh happy day!", numUpdates, "markets have been updated!");
  // fun times here
});
```

Gives error:

```
/Users/steve/stuff/marketeer-test/node_modules/augur-contracts/tx.js:18
            api.functions[contract][method].to = contracts[contract];
                                                          ^

TypeError: Cannot read property 'Backstops' of undefined
    at new module.exports (/Users/steve/stuff/marketeer-test/node_modules/augur-contracts/tx.js:18:59)
    at /Users/steve/stuff/marketeer-test/node_modules/ethereumjs-connect/index.js:72:36
    at /Users/steve/stuff/marketeer-test/node_modules/ethrpc/index.js:608:21
    at /Users/steve/stuff/marketeer-test/node_modules/ethrpc/node_modules/async/lib/async.js:52:16
    at /Users/steve/stuff/marketeer-test/node_modules/ethrpc/node_modules/async/lib/async.js:264:21
    at /Users/steve/stuff/marketeer-test/node_modules/ethrpc/node_modules/async/lib/async.js:44:16
    at /Users/steve/stuff/marketeer-test/node_modules/ethrpc/index.js:601:40
    at Object.parse (/Users/steve/stuff/marketeer-test/node_modules/ethrpc/index.js:215:24)
    at Request._callback (/Users/steve/stuff/marketeer-test/node_modules/ethrpc/index.js:501:22)
    at Request.self.callback (/Users/steve/stuff/marketeer-test/node_modules/ethrpc/node_modules/request/request.js:198:22)
```

**Comment by tinybike** [comment]
@steveklebanoff This repo is no longer maintained!
